/* Seed data - synced from lib/data.ts for Node.js seed script */

module.exports.coursesData = [
  {
    id: "1",
    thumbnail: "/course-1.png",
    titleAr: "تطوير تطبيقات الويب الحديثة",
    titleEn: "Modern Web Development",
    instructorAr: "أحمد محمد",
    instructorEn: "Ahmed Mohammed",
    instructorAvatar: "/user-avatar.png",
    rating: 4.8,
    students: 2450,
    price: 199,
    originalPrice: 399,
    category: "programming",
    level: "intermediate",
    hours: 42,
    lessons: 68,
    sections: 12,
    updatedAt: "2026-01",
    language: "ar",
    descriptionAr: "تعلّم بناء تطبيقات ويب احترافية باستخدام أحدث التقنيات مثل React و Next.js و TypeScript.",
    descriptionEn: "Learn to build professional web applications using React, Next.js, and TypeScript.",
  },
  {
    id: "2",
    thumbnail: "/course-2.png",
    titleAr: "تصميم واجهات المستخدم UI/UX",
    titleEn: "UI/UX Design Masterclass",
    instructorAr: "سارة أحمد",
    instructorEn: "Sara Ahmed",
    instructorAvatar: "/user-avatar.png",
    rating: 4.9,
    students: 1890,
    price: 149,
    originalPrice: 299,
    category: "design",
    level: "beginner",
    hours: 36,
    lessons: 52,
    sections: 10,
    updatedAt: "2026-02",
    language: "ar",
    descriptionAr: "أتقن فن تصميم واجهات المستخدم وتجربة المستخدم باستخدام Figma.",
    descriptionEn: "Master UI/UX design using Figma.",
  },
  {
    id: "3",
    thumbnail: "/course-3.png",
    titleAr: "التسويق الرقمي الشامل",
    titleEn: "Complete Digital Marketing",
    instructorAr: "خالد العلي",
    instructorEn: "Khalid Al-Ali",
    instructorAvatar: "/user-avatar.png",
    rating: 4.7,
    students: 3200,
    price: 129,
    originalPrice: 259,
    category: "marketing",
    level: "beginner",
    hours: 28,
    lessons: 45,
    sections: 8,
    updatedAt: "2026-01",
    language: "ar",
    descriptionAr: "دورة شاملة في التسويق الرقمي تغطي SEO و إعلانات Google و وسائل التواصل الاجتماعي.",
    descriptionEn: "Comprehensive digital marketing covering SEO, Google Ads, and social media.",
  },
  {
    id: "4",
    thumbnail: "/course-4.jpg",
    titleAr: "تحليل البيانات مع Python",
    titleEn: "Data Analysis with Python",
    instructorAr: "نورة السالم",
    instructorEn: "Noura Al-Salem",
    instructorAvatar: "/user-avatar.png",
    rating: 4.6,
    students: 1560,
    price: 179,
    originalPrice: 359,
    category: "data",
    level: "intermediate",
    hours: 38,
    lessons: 60,
    sections: 11,
    updatedAt: "2026-02",
    language: "ar",
    descriptionAr: "تعلّم تحليل البيانات باستخدام Python و Pandas و NumPy و Matplotlib.",
    descriptionEn: "Learn data analysis with Python, Pandas, NumPy, and Matplotlib.",
  },
  {
    id: "5",
    thumbnail: "/course-1.png",
    titleAr: "إدارة المشاريع الاحترافية",
    titleEn: "Professional Project Management",
    instructorAr: "محمد الحربي",
    instructorEn: "Mohammed Al-Harbi",
    instructorAvatar: "/user-avatar.png",
    rating: 4.5,
    students: 980,
    price: 0,
    originalPrice: 0,
    category: "business",
    level: "advanced",
    hours: 24,
    lessons: 40,
    sections: 7,
    updatedAt: "2025-12",
    language: "ar",
    descriptionAr: "أتقن إدارة المشاريع وفق منهجيات Agile و Scrum.",
    descriptionEn: "Master project management with Agile and Scrum.",
  },
  {
    id: "6",
    thumbnail: "/course-3.png",
    titleAr: "تطبيقات الجوال مع Flutter",
    titleEn: "Mobile Apps with Flutter",
    instructorAr: "فهد الدوسري",
    instructorEn: "Fahad Al-Dosari",
    instructorAvatar: "/user-avatar.png",
    rating: 4.8,
    students: 1340,
    price: 219,
    originalPrice: 449,
    category: "programming",
    level: "intermediate",
    hours: 50,
    lessons: 78,
    sections: 14,
    updatedAt: "2026-03",
    language: "ar",
    descriptionAr: "ابنِ تطبيقات جوال رائعة لنظامي iOS و Android باستخدام Flutter و Dart.",
    descriptionEn: "Build mobile apps for iOS and Android with Flutter and Dart.",
  },
]

module.exports.instructorsData = [
  { id: "1", nameAr: "أحمد محمد", nameEn: "Ahmed Mohammed", titleAr: "مطور ويب أول", titleEn: "Senior Web Developer", avatar: "/user-avatar.png", courses: 12, students: 8500, rating: 4.8 },
  { id: "2", nameAr: "سارة أحمد", nameEn: "Sara Ahmed", titleAr: "مصممة UI/UX", titleEn: "UI/UX Designer", avatar: "/user-avatar.png", courses: 8, students: 6200, rating: 4.9 },
  { id: "3", nameAr: "خالد العلي", nameEn: "Khalid Al-Ali", titleAr: "خبير تسويق رقمي", titleEn: "Digital Marketing Expert", avatar: "/user-avatar.png", courses: 6, students: 9800, rating: 4.7 },
  { id: "4", nameAr: "نورة السالم", nameEn: "Noura Al-Salem", titleAr: "عالمة بيانات", titleEn: "Data Scientist", avatar: "/user-avatar.png", courses: 5, students: 4200, rating: 4.6 },
]
