export const coursesData = [
  {
    id: "1",
    thumbnail: "/course-1.png",
    titleAr: "تطوير تطبيقات الويب الحديثة",
    titleEn: "Modern Web Development",
    instructorAr: "أحمد محمد",
    instructorEn: "Ahmed Mohammed",
    instructorAvatar: "/user-avatar.png",
    rating: 4.8,
    students: 2450,
    price: 199,
    originalPrice: 399,
    category: "programming",
    level: "intermediate",
    hours: 42,
    lessons: 68,
    sections: 12,
    updatedAt: "2026-01",
    language: "ar",
    descriptionAr: "تعلّم بناء تطبيقات ويب احترافية باستخدام أحدث التقنيات مثل React و Next.js و TypeScript. ستتعلم من الصفر حتى الاحتراف مع مشاريع عملية حقيقية.",
    descriptionEn: "Learn to build professional web applications using the latest technologies like React, Next.js, and TypeScript. From zero to hero with real-world projects.",
  },
  {
    id: "2",
    thumbnail: "/course-2.png",
    titleAr: "تصميم واجهات المستخدم UI/UX",
    titleEn: "UI/UX Design Masterclass",
    instructorAr: "سارة أحمد",
    instructorEn: "Sara Ahmed",
    instructorAvatar: "/user-avatar.png",
    rating: 4.9,
    students: 1890,
    price: 149,
    originalPrice: 299,
    category: "design",
    level: "beginner",
    hours: 36,
    lessons: 52,
    sections: 10,
    updatedAt: "2026-02",
    language: "ar",
    descriptionAr: "أتقن فن تصميم واجهات المستخدم وتجربة المستخدم باستخدام Figma. تعلّم المبادئ الأساسية والتقنيات المتقدمة لإنشاء تصاميم مذهلة.",
    descriptionEn: "Master the art of UI/UX design using Figma. Learn fundamental principles and advanced techniques to create stunning designs.",
  },
  {
    id: "3",
    thumbnail: "/course-3.png",
    titleAr: "التسويق الرقمي الشامل",
    titleEn: "Complete Digital Marketing",
    instructorAr: "خالد العلي",
    instructorEn: "Khalid Al-Ali",
    instructorAvatar: "/user-avatar.png",
    rating: 4.7,
    students: 3200,
    price: 129,
    originalPrice: 259,
    category: "marketing",
    level: "beginner",
    hours: 28,
    lessons: 45,
    sections: 8,
    updatedAt: "2026-01",
    language: "ar",
    descriptionAr: "دورة شاملة في التسويق الرقمي تغطي SEO و إعلانات Google و وسائل التواصل الاجتماعي والتسويق بالمحتوى وتحليلات البيانات.",
    descriptionEn: "A comprehensive digital marketing course covering SEO, Google Ads, social media, content marketing, and data analytics.",
  },
  {
    id: "4",
    thumbnail: "/course-4.jpg",
    titleAr: "تحليل البيانات مع Python",
    titleEn: "Data Analysis with Python",
    instructorAr: "نورة السالم",
    instructorEn: "Noura Al-Salem",
    instructorAvatar: "/user-avatar.png",
    rating: 4.6,
    students: 1560,
    price: 179,
    originalPrice: 359,
    category: "data",
    level: "intermediate",
    hours: 38,
    lessons: 60,
    sections: 11,
    updatedAt: "2026-02",
    language: "ar",
    descriptionAr: "تعلّم تحليل البيانات باستخدام Python و Pandas و NumPy و Matplotlib. من جمع البيانات وتنظيفها إلى التحليل والتصور البصري.",
    descriptionEn: "Learn data analysis with Python, Pandas, NumPy, and Matplotlib. From data collection and cleaning to analysis and visualization.",
  },
  {
    id: "5",
    thumbnail: "/course-1.png",
    titleAr: "إدارة المشاريع الاحترافية",
    titleEn: "Professional Project Management",
    instructorAr: "محمد الحربي",
    instructorEn: "Mohammed Al-Harbi",
    instructorAvatar: "/user-avatar.png",
    rating: 4.5,
    students: 980,
    price: 0,
    originalPrice: 0,
    category: "business",
    level: "advanced",
    hours: 24,
    lessons: 40,
    sections: 7,
    updatedAt: "2025-12",
    language: "ar",
    descriptionAr: "أتقن إدارة المشاريع وفق منهجيات Agile و Scrum. تعلّم أدوات وتقنيات إدارة المشاريع الاحترافية.",
    descriptionEn: "Master project management with Agile and Scrum methodologies. Learn professional project management tools and techniques.",
  },
  {
    id: "6",
    thumbnail: "/course-3.png",
    titleAr: "تطبيقات الجوال مع Flutter",
    titleEn: "Mobile Apps with Flutter",
    instructorAr: "فهد الدوسري",
    instructorEn: "Fahad Al-Dosari",
    instructorAvatar: "/user-avatar.png",
    rating: 4.8,
    students: 1340,
    price: 219,
    originalPrice: 449,
    category: "programming",
    level: "intermediate",
    hours: 50,
    lessons: 78,
    sections: 14,
    updatedAt: "2026-03",
    language: "ar",
    descriptionAr: "ابنِ تطبيقات جوال رائعة لنظامي iOS و Android باستخدام Flutter و Dart. من الأساسيات حتى نشر التطبيق على المتاجر.",
    descriptionEn: "Build stunning mobile apps for iOS and Android with Flutter and Dart. From basics to publishing on app stores.",
  },
]

export const instructorsData = [
  {
    id: "1",
    nameAr: "أحمد محمد",
    nameEn: "Ahmed Mohammed",
    titleAr: "مطور ويب أول",
    titleEn: "Senior Web Developer",
    avatar: "/user-avatar.png",
    courses: 12,
    students: 8500,
    rating: 4.8,
  },
  {
    id: "2",
    nameAr: "سارة أحمد",
    nameEn: "Sara Ahmed",
    titleAr: "مصممة UI/UX",
    titleEn: "UI/UX Designer",
    avatar: "/user-avatar.png",
    courses: 8,
    students: 6200,
    rating: 4.9,
  },
  {
    id: "3",
    nameAr: "خالد العلي",
    nameEn: "Khalid Al-Ali",
    titleAr: "خبير تسويق رقمي",
    titleEn: "Digital Marketing Expert",
    avatar: "/user-avatar.png",
    courses: 6,
    students: 9800,
    rating: 4.7,
  },
  {
    id: "4",
    nameAr: "نورة السالم",
    nameEn: "Noura Al-Salem",
    titleAr: "عالمة بيانات",
    titleEn: "Data Scientist",
    avatar: "/user-avatar.png",
    courses: 5,
    students: 4200,
    rating: 4.6,
  },
]

export const testimonialsData = [
  {
    id: "1",
    nameAr: "عبدالله الشمري",
    nameEn: "Abdullah Al-Shammari",
    roleAr: "مطور ويب",
    roleEn: "Web Developer",
    avatar: "/user-avatar.png",
    textAr: "منصة رائعة غيّرت مسيرتي المهنية بالكامل. الدورات عالية الجودة والمدربون متميزون. أنصح الجميع بالانضمام.",
    textEn: "An amazing platform that completely changed my career path. High-quality courses and outstanding instructors. I recommend everyone to join.",
    rating: 5,
  },
  {
    id: "2",
    nameAr: "منى العتيبي",
    nameEn: "Mona Al-Otaibi",
    roleAr: "مصممة جرافيك",
    roleEn: "Graphic Designer",
    avatar: "/user-avatar.png",
    textAr: "تجربة تعليمية مميزة! المحتوى منظم وسهل الفهم. حصلت على شهادتي وتمكنت من الحصول على وظيفة أحلامي.",
    textEn: "An outstanding learning experience! The content is well-organized and easy to understand. I got my certificate and landed my dream job.",
    rating: 5,
  },
  {
    id: "3",
    nameAr: "فيصل الحربي",
    nameEn: "Faisal Al-Harbi",
    roleAr: "مدير مشاريع",
    roleEn: "Project Manager",
    avatar: "/user-avatar.png",
    textAr: "أفضل منصة تعليمية عربية واجهتها. الدعم الفني ممتاز والمجتمع التعليمي نشط ومفيد جداً.",
    textEn: "The best Arabic educational platform I've encountered. Excellent technical support and a very active and helpful learning community.",
    rating: 4,
  },
  {
    id: "4",
    nameAr: "هند الزهراني",
    nameEn: "Hind Al-Zahrani",
    roleAr: "محللة بيانات",
    roleEn: "Data Analyst",
    avatar: "/user-avatar.png",
    textAr: "الدورات التدريبية عملية ومبنية على مشاريع حقيقية. استفدت كثيراً من المحتوى وتمكنت من تطوير مهاراتي بشكل كبير.",
    textEn: "The courses are practical and project-based. I benefited greatly from the content and significantly developed my skills.",
    rating: 5,
  },
]

export const courseCurriculum = [
  {
    titleAr: "مقدمة في الدورة",
    titleEn: "Course Introduction",
    lessons: [
      { id: "l1", titleAr: "مرحباً بك في الدورة", titleEn: "Welcome to the Course", duration: "5:30", free: true },
      { id: "l2", titleAr: "نظرة عامة على المنهج", titleEn: "Curriculum Overview", duration: "8:15", free: true },
      { id: "l3", titleAr: "إعداد بيئة العمل", titleEn: "Setting Up Your Environment", duration: "12:45", free: false },
    ],
  },
  {
    titleAr: "الأساسيات",
    titleEn: "Fundamentals",
    lessons: [
      { id: "l4", titleAr: "المفاهيم الأساسية", titleEn: "Core Concepts", duration: "18:20", free: false },
      { id: "l5", titleAr: "أنماط التصميم", titleEn: "Design Patterns", duration: "22:10", free: false },
      { id: "l6", titleAr: "أفضل الممارسات", titleEn: "Best Practices", duration: "15:45", free: false },
      { id: "l7", titleAr: "تمارين عملية", titleEn: "Hands-on Exercises", duration: "25:30", free: false },
    ],
  },
  {
    titleAr: "مستوى متقدم",
    titleEn: "Advanced Level",
    lessons: [
      { id: "l8", titleAr: "تقنيات متقدمة", titleEn: "Advanced Techniques", duration: "28:15", free: false },
      { id: "l9", titleAr: "تحسين الأداء", titleEn: "Performance Optimization", duration: "20:40", free: false },
      { id: "l10", titleAr: "مشروع تطبيقي", titleEn: "Practical Project", duration: "45:00", free: false },
    ],
  },
  {
    titleAr: "المشروع النهائي",
    titleEn: "Final Project",
    lessons: [
      { id: "l11", titleAr: "متطلبات المشروع", titleEn: "Project Requirements", duration: "10:00", free: false },
      { id: "l12", titleAr: "بناء المشروع", titleEn: "Building the Project", duration: "55:00", free: false },
      { id: "l13", titleAr: "النشر والاختبار", titleEn: "Deployment & Testing", duration: "30:00", free: false },
    ],
  },
]
